export const FETCH_AVATAR = 'FETCH_AVATAR';
export const FETCH_AVATAR_SUCCESS = 'FETCH_AVATAR_SUCCESS';
export const FETCH_AVATAR_ERROR = 'FETCH_AVATAR_ERROR';
export const CHANGE_AVATAR = 'CHANGE_AVATAR';
export const CHANGE_AVATAR_SUCCESS = 'CHANGE_AVATAR_SUCCESS';
export const CHANGE_AVATAR_ERROR = 'CHANGE_AVATAR_ERROR';