export const SET_NICKNAME = 'SET_NICKNAME';
export const SET_NICKNAME_ERROR = 'SET_NICKNAME_ERROR';
export const CHANGE_NICKNAME = 'CHANGE_NICKNAME';
export const CHANGE_NICKNAME_SUCCESS = 'CHANGE_NICKNAME_SUCCESS';
export const CHANGE_NICKNAME_ERROR = 'CHANGE_NICKNAME_ERROR';
export const FETCH_NICKNAME = 'FETCH_NICKNAME';
export const FETCH_NICKNAME_SUCCESS = 'FETCH_NICKNAME_SUCCESS';
export const FETCH_NICKNAME_ERROR = 'FETCH_NICKNAME_ERROR';
